apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-marc
  labels:
    app: capstone-marc
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-marc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-marc
    spec:
      containers:
        - image: marcemad/capstone-marc
          imagePullPolicy: Always
          name: capstone-marc
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-marc
  labels:
    app: capstone-marc
spec:
  type: LoadBalancer
  selector:
    app: capstone-marc
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
